name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-gi gir1.2-secret-1 python3-requests libarchive-tools pipx
          pipx install ruff
      - name: Lint
        run: ruff check --select E,F,W,B --ignore E501 crisol tests
      - name: Unit tests
        run: /usr/bin/python3 -m unittest discover -s tests -v
